### PR TITLE
Adding additional height query commands

### PR DESCRIPTION
**Pull request by Shawson**
I want to use this script from another script on my raspberry pi which calls the move_to method from physical button presses.  I also wish to implement the recording of height presets on button long-press, so need to be able to query the desk's current height if it has been adjusted manually.

### CODE REVIEW

**Comment by rhyst** [comment]
Hey, sorry for delayed response. 

I'm confused about the purpose of this change. You want to run the script as a server and have it print the height on the server when it receives the `get_height` command from the client?

If that is the case I think you can just do the same thing as for the non server version i.e. send a a request with no command:

```
idasen-controller --forward
```

Please, let me know if I have not understood!

**Comment by voruti** [comment]
Wouldn't it then make sense to simply add --forward with no command to this whitelist? I think that would be less confusing ... :thinking:

**Comment by rhyst** [comment]
This is confusing to me because `--forward` already works on its own as far as I can tell.

**Comment by voruti** [comment]
> This is confusing to me because `--forward` already works on its own as far as I can tell.

Not for me:
```bash
$ idasen-controller.exe --forward

$
```
There's no output here (on the "client") ...

... but there's output at the server:
```bash
$ idasen-controller.exe --server
Connected AB:CD:EF:01:23:45
Server listening
Received command
Height:  751mm
```

**Comment by rhyst** [comment]
There's currently nothing in the code that prints values on the client side, and there's nothing in this PR that would make that work which is why I assumed @Shawson meant printing the the values on the server side.

**Comment by Shawson** [comment]
indeed- writing out at the clientside is fine enough for my usage as i just parse the result out of systemd status.  I'll update the PR to just update to simply forward an empty command

**Comment by Shawson** [comment]
Made that update and works just as great for my purposes!

**Comment by rhyst** [comment]
I'm very confused by this. I don't think this does anything? It works exactly as you suggested with no modifications.

**Comment by Shawson** [comment]
...yea you're right.  I'm sure it didn't used to log the desk height on connect, but seems fine now.  Guess I don't need these changes!

**Pull request closed without merging**
